# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/housing-ageron-nbdev',
                'doc_host': 'https://BriceChivu.github.io',
                'git_url': 'https://github.com/BriceChivu/housing-ageron-nbdev',
                'lib_path': 'housing_ageron_nbdev'},
  'syms': {'housing_ageron_nbdev.core': {'housing_ageron_nbdev.core.foo': ('core.html#foo', 'housing_ageron_nbdev/core.py')}}}
