# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_train_test_split.ipynb.

# %% auto 0
__all__ = ['get_project_path', 'load_housing_raw_data']

# %% ../nbs/00_train_test_split.ipynb 8
def get_project_path():
    """
    Get the path of the root project
    :return: Path
    """
    return Path.cwd().parent.resolve()

# %% ../nbs/00_train_test_split.ipynb 11
def load_housing_raw_data():
    project_path = get_project_path()
    return pd.read_excel(project_path / "data" / "raw" / "housing.xlsx")
