# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_train_test_split.ipynb.

# %% auto 0
__all__ = ['get_project_path', 'plot_correlation']

# %% ../nbs/00_train_test_split.ipynb 8
def get_project_path() -> Path:
    """
    Get the path of the root project
    """
    return Path.cwd().parent.resolve()


# %% ../nbs/00_train_test_split.ipynb 12
def plot_correlation(
    df: pd.DataFrame,  # dataframe for which to plot the correlation matrix
):
    '''
    Plot a correlation matrix
    '''
    fig, ax = plt.subplots(figsize=(20, 10))
    corr = df.corr(numeric_only=True)
    ax = sns.heatmap(corr, square=True, ax=ax, annot=True, cmap="coolwarm")
    ax.set_title("Correlation of each feature")
    plt.tight_layout()
    plt.show()

