# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_train_test_split.ipynb.

# %% auto 0
__all__ = ['get_project_path']

# %% ../nbs/00_train_test_split.ipynb 5
import matplotlib.pyplot as plt
import matplotlib
import pandas as pd
import numpy as np
from pathlib import Path

# %% ../nbs/00_train_test_split.ipynb 7
def get_project_path()->Path:
    """
    Get the path of the root project
    """
    return Path.cwd().parent.resolve()
